
import java.awt.Color;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lab803
 */
public class Interface extends javax.swing.JFrame {
   private Editor1 editor = new Editor1();
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon("editor.png").getImage());
        this.setTitle("Editor de Texto");
       editor.setArea(jTextArea1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoFonte = new javax.swing.ButtonGroup();
        GrupoCor = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Formatar = new javax.swing.JMenuBar();
        JMenuArquivo = new javax.swing.JMenu();
        jMenuItemNovo = new javax.swing.JMenuItem();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuItemSalvar = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuItemCopiar = new javax.swing.JMenuItem();
        jMenuItemRecortar = new javax.swing.JMenuItem();
        jMenuItemColar = new javax.swing.JMenuItem();
        jMenuItemSeleciorTudo = new javax.swing.JMenuItem();
        jMenuFormatar = new javax.swing.JMenu();
        jMenuFonte = new javax.swing.JMenu();
        jRadioButtonItemArial = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonItemTimes = new javax.swing.JRadioButtonMenuItem();
        jMenuCor = new javax.swing.JMenu();
        jRadioButtonItemAzul = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonItemPreto = new javax.swing.JRadioButtonMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setVisible(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jInternalFrame1.getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jInternalFrame1, java.awt.BorderLayout.CENTER);

        JMenuArquivo.setMnemonic('a');
        JMenuArquivo.setText("Arquivo");

        jMenuItemNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNovo.setText("Novo");
        jMenuItemNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoActionPerformed(evt);
            }
        });
        JMenuArquivo.add(jMenuItemNovo);

        jMenuItemAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAbrir.setText("Abrir");
        jMenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirActionPerformed(evt);
            }
        });
        JMenuArquivo.add(jMenuItemAbrir);

        jMenuItemSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSalvar.setText("Salvar");
        jMenuItemSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalvarActionPerformed(evt);
            }
        });
        JMenuArquivo.add(jMenuItemSalvar);

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        JMenuArquivo.add(jMenuItemSair);

        Formatar.add(JMenuArquivo);

        jMenuEditar.setMnemonic('f');
        jMenuEditar.setText("Editar");

        jMenuItemCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCopiar.setText("Copiar");
        jMenuItemCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCopiarActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemCopiar);

        jMenuItemRecortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemRecortar.setText("Recortar");
        jMenuItemRecortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRecortarActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemRecortar);

        jMenuItemColar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemColar.setText("Colar");
        jMenuItemColar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemColarActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemColar);

        jMenuItemSeleciorTudo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSeleciorTudo.setText("Selecionar Tudo");
        jMenuItemSeleciorTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSeleciorTudoActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemSeleciorTudo);

        Formatar.add(jMenuEditar);

        jMenuFormatar.setMnemonic('h');
        jMenuFormatar.setText("Formatar");

        jMenuFonte.setText("Fonte");

        GrupoFonte.add(jRadioButtonItemArial);
        jRadioButtonItemArial.setSelected(true);
        jRadioButtonItemArial.setText("Arial");
        jRadioButtonItemArial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonItemArialActionPerformed(evt);
            }
        });
        jMenuFonte.add(jRadioButtonItemArial);

        GrupoFonte.add(jRadioButtonItemTimes);
        jRadioButtonItemTimes.setText("Times");
        jRadioButtonItemTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonItemTimesActionPerformed(evt);
            }
        });
        jMenuFonte.add(jRadioButtonItemTimes);

        jMenuFormatar.add(jMenuFonte);

        jMenuCor.setText("Cor");

        GrupoCor.add(jRadioButtonItemAzul);
        jRadioButtonItemAzul.setSelected(true);
        jRadioButtonItemAzul.setText("Azul");
        jRadioButtonItemAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonItemAzulActionPerformed(evt);
            }
        });
        jMenuCor.add(jRadioButtonItemAzul);

        GrupoCor.add(jRadioButtonItemPreto);
        jRadioButtonItemPreto.setText("Preto");
        jRadioButtonItemPreto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonItemPretoActionPerformed(evt);
            }
        });
        jMenuCor.add(jRadioButtonItemPreto);

        jMenuFormatar.add(jMenuCor);

        Formatar.add(jMenuFormatar);

        jMenuAjuda.setMnemonic('x');
        jMenuAjuda.setText("Ajuda");

        jMenuItem9.setText("Sobre");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItem9);

        Formatar.add(jMenuAjuda);

        setJMenuBar(Formatar);

        setBounds(0, 0, 626, 506);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirActionPerformed
        // TODO add your handling code here:
        editor.abrir(this, jInternalFrame1);
        
    }//GEN-LAST:event_jMenuItemAbrirActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        editor.sobre(this);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItemColarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemColarActionPerformed
        // TODO add your handling code here:
        editor.colar();
    }//GEN-LAST:event_jMenuItemColarActionPerformed

    private void jMenuItemNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovoActionPerformed
        // TODO add your handling code here:
        editor.novo(jInternalFrame1);
    }//GEN-LAST:event_jMenuItemNovoActionPerformed

    private void jMenuItemSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalvarActionPerformed
        // TODO add your handling code here:
        editor.salvar(this, jInternalFrame1);
    }//GEN-LAST:event_jMenuItemSalvarActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        editor.sair();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCopiarActionPerformed
        // TODO add your handling code here:
        editor.copiar();
    }//GEN-LAST:event_jMenuItemCopiarActionPerformed

    private void jMenuItemRecortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRecortarActionPerformed
        // TODO add your handling code here:
        editor.recortar();
    }//GEN-LAST:event_jMenuItemRecortarActionPerformed

    private void jMenuItemSeleciorTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSeleciorTudoActionPerformed
        // TODO add your handling code here:
        editor.selecionarTudo();
    }//GEN-LAST:event_jMenuItemSeleciorTudoActionPerformed

    private void jRadioButtonItemArialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonItemArialActionPerformed
        // TODO add your handling code here:
        editor.configurarFonte(jRadioButtonItemArial.getText());
    }//GEN-LAST:event_jRadioButtonItemArialActionPerformed

    private void jRadioButtonItemTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonItemTimesActionPerformed
        // TODO add your handling code here:
        editor.configurarFonte(jRadioButtonItemTimes.getText());
    }//GEN-LAST:event_jRadioButtonItemTimesActionPerformed

    private void jRadioButtonItemAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonItemAzulActionPerformed
        // TODO add your handling code here:
        editor.configurarCor(Color.BLUE);
    }//GEN-LAST:event_jRadioButtonItemAzulActionPerformed

    private void jRadioButtonItemPretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonItemPretoActionPerformed
        // TODO add your handling code here:
        editor.configurarCor(Color.BLACK);
    }//GEN-LAST:event_jRadioButtonItemPretoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Formatar;
    private javax.swing.ButtonGroup GrupoCor;
    private javax.swing.ButtonGroup GrupoFonte;
    private javax.swing.JMenu JMenuArquivo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuCor;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuFonte;
    private javax.swing.JMenu jMenuFormatar;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemColar;
    private javax.swing.JMenuItem jMenuItemCopiar;
    private javax.swing.JMenuItem jMenuItemNovo;
    private javax.swing.JMenuItem jMenuItemRecortar;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSalvar;
    private javax.swing.JMenuItem jMenuItemSeleciorTudo;
    private javax.swing.JRadioButtonMenuItem jRadioButtonItemArial;
    private javax.swing.JRadioButtonMenuItem jRadioButtonItemAzul;
    private javax.swing.JRadioButtonMenuItem jRadioButtonItemPreto;
    private javax.swing.JRadioButtonMenuItem jRadioButtonItemTimes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
